# LEARNING OUTCOMES

After taking the CE course, participants will:

1. Understand data science is the process of defining the problem with business knowledge, gathering needed data from various sources, developing models, extracting insight and recommend actions.
1. Get familiar with the cloud-based big data platform (Hadoop/Hive/Spark/GPU etc.) that are widely used in the development and production setting for industry and know how to quickly transit from academia environment to enterprise environment. 
1. Get familiar with data extraction, transformation and load from various database systems such that participates can learn how to become self-sufficient to get needed data in enterprise environment.
1. Understand how to leverage interactive dashboard to present insight and results and communicate efficient with business partners and customers.
1. Understand what data scientists “in the wild” are doing and better prepared to be data scientist in the future.
1. Learn how to encode a real problem to a data science problem, search for the right data, preprocess data and deploy of analytical results through a case study.
1. Get familiar with how to achieve high-performance computing for standard statistical procedures with big data infrastructure.
