--- 
title: "The Science and Art of Data"
author: "Hui Lin and Ming Li"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
   config:
     toc:
       collapse: subsection
       scroll_highlight: yes
       before: null
       after: null
     toolbar:
       position: fixed
     edit : null
     download: ["pdf", "epub", "mobi"]
     search: yes
     fontsettings:
       theme: white
       family: sans
       size: 2
     sharing:
       facebook: yes
       twitter: yes
       google: no
       weibo: no
       instapper: no
       vk: no
       all: ['facebook', 'google', 'twitter', 'weibo', 'instapaper']
  bookdown::pdf_book:
    keep_tex: yes
documentclass: book
bibliography: [bibliography.bib]
biblio-style: apalike
link-citations: yes
description: "This is the handouts for CE course at JSM 2017"
---


```{r, echo=FALSE}
#setwd("/Users/happyrabbit/Documents/GitHub/CE_JSM2017")
#bookdown::render_book("index.Rmd", "bookdown::gitbook")
```

# Copyright Statement {-}

This work is licensed under a Creative Commons Attribution-No Derivative Works 3.0 United States License.

Copyright is retained by Hui Lin and Ming Li in all non-U.S. jurisdictions, but permission to use these materials in teaching is still granted, provided the authorship and licensing information here is displayed.

The authors have striven to minimize the number of errors, but no guarantee is made as to the accuracy of the contents of this book.


# About the Authors {-}

**Hui Lin** is currently Data Scientist at DuPont Pioneer. She is a leader within DuPont at applying advanced data science to enhance Marketing and Sales effectiveness. She has been providing statistical leadership for a broad range of predictive analytics and market research analysis since 2013. She is the co-founder of Central Iowa R User Group, blogger of scientistcafe.com and program Chair of Statistics in Marketing Section of ASA for 2018. She enjoys making analytics accessible to a broad audience and teaches tutorials and workshops for practitioners on data science. 

She holds MS and Ph.D. in statistics from Iowa State University, BS in mathematical statistics from Beijing Normal University.

**Ming Li** is currently a Sr. Data Scientist at Amazon. He was Data Scientist at Wal-Mart and an Adjunct Faculty of Department and Marketing and Business Analytics in TAMU – Commerce. He is also the Chair of Quality & Productivity Section of ASA for 2016. He was a Statistical Leader at General Electric Global Research Center and Research Statistician at SAS Institute. He obtained his Ph.D. in Statistics from Iowa State University at 2010. With deep statistics background and a few years’ experience in data science, he has trained and mentored numerous junior data scientist with different backgrounds such as statistics, computer science, and business analytics. 


