---
title: "Introduction"
author: "Ming Li, Amazon </br> [Hui Lin](http://scientistcafe.com), DuPont"
date: "July 30, 2017 @ JSM2017"
output: 
  slidy_presentation: 
    footer: "http://scientistcafe.com"
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About Us: Ming Li

- PhD in Statistics from Iowa State University 
- Sr. Data Scientist at Amazon
- Previously
    - Applied Statistics Lab of GE Global Research Center
    - Research Statistician at SAS
    - Data Scientist at Wal-Mart 

## About Us: Hui Lin

> - Language: 1st Chinese; 2nd R; 3rd English
> - Graduated from Iowa State Univ (MS & PhD in Stats)
> - Data Scientist at DuPont Pioneer
> - Co-founder of [ Central Iowa R User Group](http://www.meetup.com/Central-Iowa-R-User-Group/)
> - Scientist Cafe: http://scientistcafe.com
> - Contact: [Email](longqiman@gmail.com);   [Github](https://github.com/happyrabbit);  [Twitter](https://twitter.com/gossip_rabbit);
[Personal Website](http://linhui.org)
>- [Jokes](http://hui1987.com/jokes.html)


## Survey

> - Statistician
> - Data Scientist
> - Data Size
> - Variable Types
> - Run Time
> - Model Delivery
> - Data Access

## Time schedule

|  | Time | Topic |
|--------|-------------------------|---------------------------------------------------------|
| Slot 1 | 8.30 a.m. - 10.15 a.m. | Introduction, The art of data science, Big Data Cloud Platform |
| Slot 2 | 10.30 a.m. - 12.30 a.m. | Big Data Cloud Platform, Data Wrangling |
| Slot 3 | 2.00 p.m. - 3.15 p.m. | Data Pre-processing, Markdown, HTML5 Slides|
| Slot 4 | 3.30 p.m. - 5.00 p.m. | Shiny Dashboard, Soft Skills for Data Scientists|

## Set up

https://github.com/happyrabbit/CE_JSM2017


